### ISSUE TITLE
backspace in vim

### ISSUE THREAD

**Issue by pickfire** [sk1418/wiki#1]
Hi, I had read your interesting wiki in http://sk1418.github.io/wiki/linux/clishortcuts.html

There are actually backspace in vim which is `X`.

**Comment by sk1418** [comment]
thx, those keys are not one to one mappings. Since I am much more familiar with vim than emacs, those vim cmds can remind me what does the emacs short-cut do. The `X` is to remove the char before cursor in normal mode. It is not exactly same as insert mode `CTRL-H` or backspace, e.g. `X` won't remove linebreaks, however backspace/ctrl-h does. The correct mapping on vim side is the ctrl-h in INSERT Mode. But you are correct, `X` is something like that.
